### PR TITLE
Implemented the code to fix the Bug_5359

### PR DESCRIPTION
**Pull request by shahanemahesh**

### CODE REVIEW

**Comment by MeniKadosh1** [comment]
please do not push before beta process ends.

**Comment by shahanemahesh** [comment]
User have not created his own function, he have used  the vbs function already in our vbs function "Check if date valid", so in this case then will have to change our vbs function, please let me know so we need to do that?

Sent from Nine
________________________________

**Comment by JaspreetGIT** [comment]
Let's update the VB Expression which is getting added while selecting IsDate from VB Functions

**Comment by shahanemahesh** [comment]
+Jaspreet

Sent from Nine
________________________________

**Comment by shahanemahesh** [comment]
As discussed this needs to be handled in different way so deleting the branch

**Pull request closed without merging**
